// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	GOOGLE_DRIVE_CLIENT_EMAIL: string;
	GOOGLE_DRIVE_CLIENT_ID: string;
	GOOGLE_DRIVE_PRIVATE_KEY: string;
	ANTHROPIC_API_KEY: string;
	AI: Ai;
}
