# wrangler.toml

name = "blog-automation"
node_compat = true
compatibility_date = "2024-07-31"

[ai]
binding = "AI"

[vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "SUSUKO"
bucket_name = "pinagtagpo-pero-di-tinadha"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"